### ISSUE TITLE
Inspect fetchone() returns expected request_id

### ISSUE THREAD

**Issue by mark-walle** [bcgov/GDX-Analytics-OpenShift-Snowplow-Gateway-Service#32]
https://github.com/bcgov/GDX-Analytics-OpenShift-Snowplow-Gateway-Service/blob/6f98d3e8e02df739a04e5410bfadb4e59c26cad1/app/app.py#L96

**Comment by lclarko** [comment]
@mark-walle Can this issue be closed?

**Comment by mark-walle** [comment]
@lclarko  No, it hasn't been resolved.

**Comment by mark-walle** [comment]
GDXDSD-3358 cc @lclarko

**Comment by veenupunyani** [comment]
This is being resolved in https://apps.itsm.gov.bc.ca/jira/browse/GDXDSD-3358

**Comment by veenupunyani** [comment]
@mark-walle https://apps.itsm.gov.bc.ca/jira/browse/GDXDSD-3358 is cancelled, can i close this issue?

**Comment by mark-walle** [comment]
@veenupunyani Yes. I'll close it now.
